keystore_path    = /var/lib/scatterweb/keystore.dat
keystore_salt    = /var/lib/scatterweb/keystore.salt
messages_db_path = /var/lib/scatterweb/messages.db
client_sock      = /run/scatterweb/client.sock
anonrouter_sock  = /run/anonrouter/daemon.sock
inbox_sock       = /run/scatterweb/inbox.sock
outbox_sock      = /run/scatterweb/outbox.sock